### ISSUE TITLE
Bug in the CFO/DTC operation - event marker is sent first

### ISSUE THREAD

**Issue by grakness** [Mu2e/otsdaq_mu2e#39]
There's a bug in the CFO/DTC firmware that upon launching a new run plan an event marker is sent first then followed by a heartbeat. For the correct STM ROC operation we always expect a heartbeat before an event marker. There's a vivado lab screenshot in the attachments.

![Screenshot_20231110_175024](https://github.com/Mu2e/otsdaq_mu2e/assets/133052220/bd574b7d-94ed-4a04-a485-e41b747ce512)

**Comment by rrivera747** [comment]
This bug should be addressed by new CFO version  CFO2023Nov09_11_22.1 

Will close after confirmation from STM team.

**Comment by rrivera747** [comment]
Bug confirmed fixed. As of today, CFO version has no open issues: CFO2024Jun21_15_22.1
