### ISSUE TITLE
Bug in the CFO/DTC operation - the first heartbeats sent do not follow the event tag number set in the runplan

### ISSUE THREAD

**Issue by grakness** [Mu2e/otsdaq_mu2e#40]
Upon launching a new plan the first few heartbeats sent (9 to be exact) do not have the event tag numbers that was set initially in the runplan. After these 9 heartbeats the following heartbeat has the event window tag number that was set in the runplan. These first 9 heartbeats look like remnants from the previous run. In the attachments there's a vivado_lab screenshot and the CFOCommands.txt file (which defines the runplan).

![Screenshot_20231110_180201](https://github.com/Mu2e/otsdaq_mu2e/assets/133052220/382190bb-dc6e-4855-ac0a-4aeb59f1f717)

![Screenshot_20231110_180005](https://github.com/Mu2e/otsdaq_mu2e/assets/133052220/ce484808-994c-448b-83ff-c9d90cedf22c)

**Comment by rrivera747** [comment]
This bug should be addressed by new CFO version  CFO2023Nov09_11_22.1 

Will close after confirmation from STM team.

**Comment by rrivera747** [comment]
Bug confirmed fixed. As of today, CFO version has no open issues: CFO2024Jun21_15_22.1
