### ISSUE TITLE
Bug in the CFO/DTC operation - event marker interval can't be set in the runplan

### ISSUE THREAD

**Issue by grakness** [Mu2e/otsdaq_mu2e#41]
There's a bug in the CFO operation that the CFO firmware does not take into account the WAIT period (event marker interval) set in the CFOCommands.txt (run plan) for the run. The interval can only be changed by writing the value to the CFO register 0x91A0. This prevents us from setting on-spill/off-spill event marker interval values in the run plan, therefore prevents us to simulate a realistic Mu2e run. This interval should be set by the run plan.

**Comment by rrivera747** [comment]
This bug should be addressed by new CFO version  CFO2023Nov09_11_22.1 

Will close after confirmation from STM team.

**Comment by rrivera747** [comment]
Bug confirmed fixed. As of today, CFO version has no open issues: CFO2024Jun21_15_22.1
