### ISSUE TITLE
Bug in the CFO/DTC operation - event markers/heartbeats are sent indefinitely

### ISSUE THREAD

**Issue by grakness** [Mu2e/otsdaq_mu2e#42]
There's a bug in the CFO operation such that the event markers/heartbeats are sent indefinitely event though a specific number is set in the runplan. The firmware does not seem to take into account the number of event markers to be sent which is defined by the LOOP command.

**Comment by rrivera747** [comment]
This bug should be addressed by new CFO version  CFO2023Nov09_11_22.1 

Will close after confirmation from STM team.

**Comment by rrivera747** [comment]
Bug confirmed fixed. As of today, CFO version has no open issues: CFO2024Jun21_15_22.1
