### ISSUE TITLE
STM CFO/DTC operation: The state machine goes in to the failed state when configuring.

### ISSUE THREAD

**Issue by emotuk2** [Mu2e/otsdaq_mu2e#45]
Below is the error I get when I try to go into Configured state from the Halted state in the state machine. I think it has something to do with the STM_VST_Config

Failure performing transition from H-Halted to C-Configured.
Exception:
:GatewaySupervisor:otsdaq/otsdaq/GatewaySupervisor/GatewaySupervisor.cc:2588
Received error message from Supervisor instance = 'FESupervisorCalo04' [LID=316] in Context 'ContextCalo04' [URL=http://mu2e-calo-04.fnal.gov:3038/].
 Error Message = :FESupervisor:FESupervisorCalo04        <>
:otsdaq/otsdaq/CoreSupervisors/CoreSupervisorBase.cc:668
Error was caught while configuring: DTCIOErrorException: CFO-DTC6 - write value 0x00001f40 to register 0x91a0... read back 0x00000000
If you do not understand this error, try checking the CFO firmware version: Nov/09/2023 11:00  raw-data: 0x23110911
:FSM-FESupervisor:FESupervisorCalo04        <>
:otsdaq/otsdaq/FiniteStateMachine/RunControlStateMachine.cc:429
Run Control Message Handling Failed with command 'Configure': :FESupervisor:FESupervisorCalo04        <>
:otsdaq/otsdaq/CoreSupervisors/CoreSupervisorBase.cc:668
Error was caught while configuring: DTCIOErrorException: CFO-DTC6 - write value 0x00001f40 to register 0x91a0... read back 0x00000000
If you do not understand this error, try checking the CFO firmware version: Nov/09/2023 11:00  raw-data: 0x23110911
 :FESupervisor:FESupervisorCalo04        <>
:otsdaq/otsdaq/CoreSupervisors/CoreSupervisorBase.cc:668
Error was caught while configuring: DTCIOErrorException: CFO-DTC6 - write value 0x00001f40 to register 0x91a0... read back 0x00000000
If you do not understand this error, try checking the CFO firmware version: Nov/09/2023 11:00  raw-data: 0x23110911
...
14/11/2023 pm (Warning):
State was changed unexpectedly from Configured to Failed. (Likely there was a error transitioning a Supervisor)
...
14/11/2023 pm (Warning):
State result not anticipated. Attempting to re-align with server.

**Comment by rrivera747** [comment]
// CFO_Register_EventWindowEmulatorIntervalTime = 0x91A0, //register deleted in Firmware version: Nov/09/2023 11:00   raw-data: 0x23110911

Removing the register was part of the fix in the CFO firmware. Now it is controlled by the Run Plan. I'm fixing the software now.

**Comment by rrivera747** [comment]
This issue is fixed with branch rrivera/cfoRunPlanBugFixes
