### ISSUE TITLE
artdaq dropping events between board reader and event builder

### ISSUE THREAD

**Issue by AndrewEdmonds11** [Mu2e/otsdaq_mu2e#47]
Documenting this bug that we saw with the STM VST. When we send ~65k off-spill events we receive either ~10k events if we use artdaqDriver, or ~40k events if we use a full ots setup. In both cases, the event builder is not taking the events quickly enough. We have tried moving to a ContainerFragment but that did not improve the situation. Eric has pointed me to a couple of PRs that may help, which I will test soon.

**Comment by normanajn** [comment]
No longer relevant
