### ISSUE TITLE
ARTDAQ_PARTITION_NUMBER vs ARTDAQ_PARTITION

### ISSUE THREAD

**Issue by pavel1murat** [Mu2e/otsdaq_mu2e#48]
(as Ryan suggested to log all Mu2e issues in otsdaq_mu2e, moving it here from **otsdaq**):  

artdaq uses an env var ARTDAQ_PARTITION_NUMBER:
https://github.com/art-daq/artdaq/blob/develop/artdaq/DAQdata/Globals.hh#L94

at the same time, otsdaq, in its configuration, uses another env var , ARTDAQ_PARTITION,
https://github.com/art-daq/otsdaq/blob/develop/tools/ots#L447
which seemingly has the same meaning and is also used in the Mu2e setup scripts

- do the two env vars represent the same parameter - the partition number used by artdaq?
- if the answer is YES, could the same variable name be used ?
- if the answer is NO, could the two names be modified to reflect the difference ?

for the reference, a grep snippet:

```
../pasha_018/srcs/otsdaq/tools/ots:447: pids=`ps aux|grep "partition_number: ${ARTDAQ_PARTITION}"|awk '{print $2}'`
../pasha_018/srcs/otsdaq/tools/ots:451: pids=`ps aux|grep "partition_${ARTDAQ_PARTITION}"|awk '{print $2}'`
../pasha_018/srcs/artdaq/artdaq/DAQdata/Globals.hh:78:   * \brief Get the current partition number, as defined by the ARTDAQ_PARTITION_NUMBER environment variable
../pasha_018/srcs/artdaq/artdaq/DAQdata/Globals.hh:94:                  auto part = getenv("ARTDAQ_PARTITION_NUMBER");  // Valid values 0-127
../pasha_018/srcs/artdaq/artdaq/DAQrate/SharedMemoryEventManager.cc:454:                                std::string envVarKey = "ARTDAQ_PARTITION_NUMBER";

```

**Comment by eflumerf** [comment]
Please repoen in art-daq/artdaq
