### ISSUE TITLE
problem with the PCIE driver v2_09_00 on mu2edaq09 (ots bundle v2_07_00)

### ISSUE THREAD

**Issue by pavel1murat** [Mu2e/otsdaq_mu2e#55]
after upgrading the DTC PCIE driver to version v2_09_00 on mu2edaq09 aand switching to v2_07_00 release of ots, I'm getting error diagnostics on any attempt to write to the DTC register:
```
mu2etrk@mu2edaq09:~/test_stand/pasha_021>dkms status
mu2e_pcie_utils/2.09.00, 3.10.0-1160.102.1.el7.x86_64, x86_64: installed (original_module exists)
pcie_linux_kernel_module/2.04.01, 3.10.0-1127.8.2.el7.x86_64, x86_64: installed (WARNING! Missing some built modules!) (WARNING! Missing some built modules!) (WARNING! Missing some built modules!)
mu2etrk@mu2edaq09:~/test_stand/pasha_021>modinfo mu2e
filename:       /lib/modules/3.10.0-1160.102.1.el7.x86_64/extra/mu2e.ko.xz
license:        GPL
description:    mu2e pcie driver
author:         Ron Rechenmacher
retpoline:      Y
rhelversion:    7.9
srcversion:     6BD0E35A5ACB10818EB697C
depends:        TRACE
vermagic:       3.10.0-1160.102.1.el7.x86_64 SMP mod_unload modversions 
signer:         DKMS module signing key
sig_key:        73:31:23:73:BE:B2:6D:4B:55:CB:F1:4D:54:0D:39:3D:11:86:DF:6B
sig_hashalgo:   sha512
mu2etrk@mu2edaq09:~/test_stand/pasha_021>echo $DTCLIB_DTC
1
mu2etrk@mu2edaq09:~/test_stand/pasha_021>my_cntl read 0x9004
0x23090211
sts=0
mu2etrk@mu2edaq09:~/test_stand/pasha_021>my_cntl write 0x91f8 0x00003f3f
12-08 12:20:57.069208             mu2edev    ERROR release_all:  - release_all dcs lock not held!
NOTE: Write value mismatch 0x3F3F vs readback 0x3F
sts=0

```

**Comment by rrivera747** [comment]
Register 0x91f8 of the DTC is only 6 bits; the behavior looks to be correct.

**Comment by pavel1murat** [comment]
writing to  0x91f8  gives an example of the diagnostics, the diagnostics is generated on ANY write, for example, when executing `$MU2E_PCIE_UTILS_DIR/dtcInterfaceLib/JAConfig.sh`
I can confirm that this problem does not happen with the ots=v2_06_11/driver=v2_04_01, that could be an additional indication of the problems with the DTC readout we're experiencing.

**Comment by pavel1murat** [comment]
one more bit of information: the same diagnostics does come up in  ots=v2_07_11/PCIE driver=v2_04_01 combination,
so most likely  it has to do with the mu2e_pcie_utils  v2_07_00 vintage

**Comment by pavel1murat** [comment]
the error reporting persists: 

```
mu2etrk@mu2edaq09:~/test_stand/pasha_023>rocUtil -l 2 -a 14 -w 0x1 write_register
02-25 11:30:40.270494                            mu2edev    ERROR release_all: DTC1 - release_all dcs lock not held!

```

1.  If that is a real error, it needs to be fixed, if the diagnostics is harmless, the severity level better be downgraded
2.  I'm using the head of mu2e_pcie_utils, as of today:
-------------------------------------------
Merge: a14c8cd 9c91aa7
Author: eflumerf <61473357+eflumerf@users.noreply.github.com>
Date:   Fri Feb 23 14:50:07 2024 -0600

    Merge pull request #35 from Mu2e/rrivera/progressCheckpointAtCaloAndTrkVSTs
    
    In preparation for artdaq software event building, re-established sub 
----------------------------------------------------------

**Comment by rrivera747** [comment]
@pavel1murat do you agree this is fixed now as of https://github.com/Mu2e/mu2e_pcie_utils/pull/37 ?
