### ISSUE TITLE
artdaq/ExternalComms/CommanderInterface.hh - an obsolete example? 

### ISSUE THREAD

**Issue by pavel1murat** [Mu2e/otsdaq_mu2e#62]
an xmlrpc communication example in artdaq/ExternalComms/CommanderInterface.hh reads 

`EXAMPLE: xmlrpc http://localhost:5235/RPC2 daq.add_config_archive_entry "EventBuilder1" "daq: {verbose: true}"`

(https://github.com/art-daq/artdaq/blob/develop/artdaq/ExternalComms/CommanderInterface.hh#L289)

when I'm trying to run this example, I'm getting the following error diagnostics: 

```
mu2etrk@mu2edaq09:~/test_stand/pasha_020>ps -efl | grep 21103 | grep -v grep
0 S mu2etrk  10141     1  5  80   0 - 806924 poll_s 12:39 pts/9   00:08:48 eventbuilder -c id: 21103 commanderPluginType: xmlrpc rank: 3 application_name: eventbuilder02 partition_number: 11
mu2etrk@mu2edaq09:~/test_stand/pasha_020>xmlrpc http://localhost:21103/RPC2 daq.add_config_archive_entry "eventbuilder02" "daq: {verbose: true}"
Failed.  Invalid specification of parameter 1 (starting at zero).  Junk after parameter specification: ': {verbose: true}'

```

 I'm doing smth wrong or the is the example is obsolete ?

**Comment by eflumerf** [comment]
Please reopen in art-daq/artdaq
