### ISSUE TITLE
mu2e_pcie_utils: the DTC driver output depends on the compilation mode (prof vs debug)

### ISSUE THREAD

**Issue by pavel1murat** [Mu2e/otsdaq_mu2e#66]
an attempt to write into the DTC register using mu2e_pcie_utils compiled in debug mode generates error diagnostics:
```
mu2etrk@mu2edaq09:~/test_stand/pasha_020>my_cntl -d 1 write 0x9168 0x68010B00
01-19 12:21:51.259549             mu2edev    ERROR release_all:  - release_all dcs lock not held!
sts=0
```

however, the same register write performed using the same version of mu2e_pcie_utils compiled with the optimization 
(prof, in our jargon) succeeds:

```
mu2etrk@mu2edaq09:~/test_stand/pasha_020_prof>my_cntl -d 1 write 0x9168 0x68010B00
sts=0
``` 
the corresponding git tag is 
`
commit 0984bfe4a5996346965df71f455cfca1bead6d0b (tag: v2_09_01, origin/develop, origin/HEAD)
`

**Comment by normanajn** [comment]
This is the intended behavior.
